
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 1m # Evaluate rules
  scrape_interval: 15s # Interval between metric collection
  scrape_timeout: 10s

  external_labels:
    environment: environzen-prometheus


rule_files:
  - /var/snap/prometheus/rules/*.rules

# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - 10.128.67.5:9093

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - environzen:9090
  - job_name: sensors
    metrics_path: /metrics
    static_configs:
    - targets:
      - 192.168.88.50
      - 192.168.88.83
      - 192.168.88.84
      - 192.168.88.85
    scrape_interval: 15s
    scrape_timeout: 10s
